<template>
  <div>
    <v-form ref="form" v-model="valid">
      <v-row>
        <v-col cols="12">
          <h1>{{ $t('$vuetify.game.title_create-game') }}</h1>
        </v-col>
      </v-row>
      <v-row>
        <v-col cols="12">
          <v-select v-model="gameType" :items="gameTypes" item-title="name" item-value="id" :clearable="true"
            :rules="[validateRequired]" :menu-props="{ 'data-test': 'field_game-type_options' }" :max-errors="5"
            :label="$t('$vuetify.game.field_game-type')" :required="true" data-test="field_game-type"
            name="field-game-type" return-object></v-select>
        </v-col>
      </v-row>
      <!-- <v-row>
        <v-col cols="12">
          {{ gameType }}
          <select-field v-model="gameType" :items="gameTypes" item-title="name" item-value="id" :clearable="true"
            :menu="true" :menu-props="{ 'data-test': 'field_game-type_options' }" :max-errors="5"
            :label="$t('$vuetify.game.field_game-type')" :required="true" data-test="field_game-type"
            name="field-game-type" return-object></select-field>
        </v-col>
      </v-row> -->
      <v-row>
        <v-col cols="12">
          <text-field v-model="maxPlayers" :rules="[validate_2_9]" :max-errors="5"
            :label="$t('$vuetify.game.field_max-players')" :required="true" data-test="field_max-players"
            type="number"></text-field>
        </v-col>
      </v-row>
      <v-row>
        <!-- 
        The game code should either be generated by the backend when this component is mounted 
        (make an API call to "reserve" the game code) if we want to display to the user ahead of time,
        OR simply create the game code in the backend in the create game request.
        -->
        <v-col cols="12">
          <v-text-field v-model="code" :label="$t('$vuetify.game.field_identifier')" disabled required
            data-test="field_game-code"></v-text-field>
        </v-col>
      </v-row>
      <v-row>
        <v-col cols="12">
          <v-btn block :loading="loading" :disabled="loading" data-test="button_submit" type="submit" @click="submit">{{
            $t('$vuetify.game.button_create-game') }}</v-btn>
        </v-col>
      </v-row>
    </v-form>
  </div>
</template>

<script>
import { makeid, reapplyPlaceholders } from '@/helpers/helpers'
import { ref } from 'vue'
import SelectField from '@/components/UI/inputs/SelectField.vue'
import TextField from '@/components/UI/inputs/TextField.vue'
import { validateBetween, validateRequired } from '@/helpers/validation'
import { VForm } from 'vuetify/components'

export default {
  components: {
    SelectField,
    TextField,
  },
  props: {
    gameRepoFactory: {
      type: Function,
      default() {
        return {
          create: (data) => {
            return new Promise(resolve => setTimeout(() => {
              return resolve(data)
            }, 1000))
          },
        }
      },
    },
    gameOptionsRepoFactory: {
      type: Function,
      default() {
        return {
          get: () => {
            return new Promise(resolve => setTimeout(() => {
              return resolve({
                gameTypes: [
                  { id: '1', name: 'Texas Holdem' },
                  { id: '2', name: 'Omaha' },
                ],
              })
            }, 1000))
          },
        }
      },
    },
  },
  setup(props) {
    const valid = ref(false)
    const loading = ref(false)
    const gameType = ref(null)
    // const gameType = ref({ id: '1', name: 'Texas Holdem' })
    const maxPlayers = ref(9)
    const code = ref(makeid(6))
    const validate_2_9 = ref(validateBetween(2, 9))

    const gameOptionsRepo = props.gameOptionsRepoFactory()
    const gameTypes = ref([])

    gameOptionsRepo.get().then((data) => {
      console.log('types')
      gameTypes.value = [
        // { id: 0, name: 'Nothing' },
        ...data.gameTypes
      ]
    })

    return {
      valid,
      loading,
      gameTypes,
      gameType,
      maxPlayers,
      code,
      validate_2_9,
      validateRequired,
    }
  },
  methods: {
    validateBetween,
    reapplyPlaceholders,
    async submit() {
      // const { valid } = await this.$refs.form.validate()
      const validationResult = await this.$refs.form.validate()
      console.log(validationResult)
      if (!validationResult.valid) {
        console.log('Form is not valid')
        return
      }

      this.loading = true
      console.log('submiting')
      setTimeout(() => (this.loading = false), 3000)
    },
  },
}
</script>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
